-- MySQL Script generated by MySQL Workbench
-- Thu 30 Jan 2025 11:06:09 AM
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bnt2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bnt2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bnt2` ;
USE `bnt2` ;

-- -----------------------------------------------------
-- Table `bnt2`.`commodity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bnt2`.`commodity` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `value` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bnt2`.`team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bnt2`.`team` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `player_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_team_player_idx` (`player_id` ASC) VISIBLE,
  CONSTRAINT `fk_team_player`
    FOREIGN KEY (`player_id`)
    REFERENCES `bnt2`.`player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bnt2`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bnt2`.`player` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `team_id` INT UNSIGNED NULL,
  `credits` INT NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `type` ENUM('pc', 'npc', 'system') NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_player_team1_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT `fk_player_team1`
    FOREIGN KEY (`team_id`)
    REFERENCES `bnt2`.`team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bnt2`.`sector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bnt2`.`sector` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bnt2`.`program`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bnt2`.`program` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `player_id` INT UNSIGNED NOT NULL,
  `content` JSON NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_program_player1_idx` (`player_id` ASC) VISIBLE,
  CONSTRAINT `fk_program_player1`
    FOREIGN KEY (`player_id`)
    REFERENCES `bnt2`.`player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bnt2`.`fleet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bnt2`.`fleet` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `player_id` INT UNSIGNED NOT NULL,
  `sector_id` INT UNSIGNED NOT NULL,
  `program_id` INT UNSIGNED NULL,
  `line` TINYINT UNSIGNED NULL,
  `data` JSON NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_fleet_player1_idx` (`player_id` ASC) VISIBLE,
  INDEX `fk_fleet_sector1_idx` (`sector_id` ASC) VISIBLE,
  INDEX `fk_fleet_program1_idx` (`program_id` ASC) VISIBLE,
  CONSTRAINT `fk_fleet_player1`
    FOREIGN KEY (`player_id`)
    REFERENCES `bnt2`.`player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fleet_sector1`
    FOREIGN KEY (`sector_id`)
    REFERENCES `bnt2`.`sector` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fleet_program1`
    FOREIGN KEY (`program_id`)
    REFERENCES `bnt2`.`program` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bnt2`.`ship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bnt2`.`ship` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `hull` TINYINT NULL DEFAULT 1,
  `engines` TINYINT NULL DEFAULT 1,
  `power` TINYINT NULL DEFAULT 1,
  `computer` TINYINT NULL DEFAULT 1,
  `sensors` TINYINT NULL DEFAULT 1,
  `weapons` TINYINT NULL DEFAULT 1,
  `shields` TINYINT NULL DEFAULT 1,
  `armour` TINYINT NULL DEFAULT 1,
  `cloak` TINYINT NULL,
  `fleet_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_ship_fleet1_idx` (`fleet_id` ASC) VISIBLE,
  CONSTRAINT `fk_ship_fleet1`
    FOREIGN KEY (`fleet_id`)
    REFERENCES `bnt2`.`fleet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bnt2`.`planet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bnt2`.`planet` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sector_id` INT UNSIGNED NOT NULL,
  `player_id` INT UNSIGNED NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_planet_sector1_idx` (`sector_id` ASC) VISIBLE,
  INDEX `fk_planet_player1_idx` (`player_id` ASC) VISIBLE,
  CONSTRAINT `fk_planet_sector1`
    FOREIGN KEY (`sector_id`)
    REFERENCES `bnt2`.`sector` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_planet_player1`
    FOREIGN KEY (`player_id`)
    REFERENCES `bnt2`.`player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bnt2`.`port`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bnt2`.`port` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sector_id` INT UNSIGNED NOT NULL,
  `commodity_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_port_sector1_idx` (`sector_id` ASC) VISIBLE,
  INDEX `fk_port_commodity1_idx` (`commodity_id` ASC) VISIBLE,
  CONSTRAINT `fk_port_sector1`
    FOREIGN KEY (`sector_id`)
    REFERENCES `bnt2`.`sector` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_port_commodity1`
    FOREIGN KEY (`commodity_id`)
    REFERENCES `bnt2`.`commodity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bnt2`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bnt2`.`cargo` (
  `fleet_id` INT UNSIGNED NOT NULL,
  `commodity_id` INT UNSIGNED NOT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`commodity_id`, `fleet_id`),
  INDEX `fk_ship_has_commodity_commodity1_idx` (`commodity_id` ASC) VISIBLE,
  INDEX `fk_cargo_fleet1_idx` (`fleet_id` ASC) VISIBLE,
  CONSTRAINT `fk_ship_has_commodity_commodity1`
    FOREIGN KEY (`commodity_id`)
    REFERENCES `bnt2`.`commodity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cargo_fleet1`
    FOREIGN KEY (`fleet_id`)
    REFERENCES `bnt2`.`fleet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bnt2`.`trade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bnt2`.`trade` (
  `port_id` INT UNSIGNED NOT NULL,
  `commodity_id` INT UNSIGNED NOT NULL,
  `demand` TINYINT NULL,
  `stock` INT NULL,
  PRIMARY KEY (`port_id`, `commodity_id`),
  INDEX `fk_port_has_commodity_commodity1_idx` (`commodity_id` ASC) VISIBLE,
  INDEX `fk_port_has_commodity_port1_idx` (`port_id` ASC) VISIBLE,
  CONSTRAINT `fk_port_has_commodity_port1`
    FOREIGN KEY (`port_id`)
    REFERENCES `bnt2`.`port` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_port_has_commodity_commodity1`
    FOREIGN KEY (`commodity_id`)
    REFERENCES `bnt2`.`commodity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bnt2`.`production`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bnt2`.`production` (
  `planet_id` INT UNSIGNED NOT NULL,
  `commodity_id` INT UNSIGNED NOT NULL,
  `quantity` VARCHAR(45) NULL,
  PRIMARY KEY (`planet_id`, `commodity_id`),
  INDEX `fk_planet_has_commodity_commodity1_idx` (`commodity_id` ASC) VISIBLE,
  INDEX `fk_planet_has_commodity_planet1_idx` (`planet_id` ASC) VISIBLE,
  CONSTRAINT `fk_planet_has_commodity_planet1`
    FOREIGN KEY (`planet_id`)
    REFERENCES `bnt2`.`planet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_planet_has_commodity_commodity1`
    FOREIGN KEY (`commodity_id`)
    REFERENCES `bnt2`.`commodity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bnt2`.`link`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bnt2`.`link` (
  `sector_id` INT UNSIGNED NOT NULL,
  `destination_id` INT UNSIGNED NOT NULL,
  `flags` ENUM('permanent', 'stealth') NULL,
  `player_id` INT UNSIGNED NULL,
  `stability` TINYINT UNSIGNED NULL,
  PRIMARY KEY (`sector_id`, `destination_id`),
  INDEX `fk_sector_has_sector_sector2_idx` (`destination_id` ASC) VISIBLE,
  INDEX `fk_sector_has_sector_sector1_idx` (`sector_id` ASC) VISIBLE,
  INDEX `fk_link_player1_idx` (`player_id` ASC) VISIBLE,
  CONSTRAINT `fk_sector_has_sector_sector1`
    FOREIGN KEY (`sector_id`)
    REFERENCES `bnt2`.`sector` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sector_has_sector_sector2`
    FOREIGN KEY (`destination_id`)
    REFERENCES `bnt2`.`sector` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_link_player1`
    FOREIGN KEY (`player_id`)
    REFERENCES `bnt2`.`player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bnt2`.`device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bnt2`.`device` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bnt2`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bnt2`.`event` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `content` TEXT NULL,
  `stamp` DATETIME NULL,
  `player_id` INT UNSIGNED NULL,
  `other_player_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_event_player1_idx` (`player_id` ASC) VISIBLE,
  INDEX `fk_event_player2_idx` (`other_player_id` ASC) VISIBLE,
  CONSTRAINT `fk_event_player1`
    FOREIGN KEY (`player_id`)
    REFERENCES `bnt2`.`player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_player2`
    FOREIGN KEY (`other_player_id`)
    REFERENCES `bnt2`.`player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bnt2`.`equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bnt2`.`equipment` (
  `fleet_id` INT UNSIGNED NOT NULL,
  `device_id` INT UNSIGNED NOT NULL,
  `quantity` TINYINT NULL,
  PRIMARY KEY (`fleet_id`, `device_id`),
  INDEX `fk_fleet_has_device_device1_idx` (`device_id` ASC) VISIBLE,
  INDEX `fk_fleet_has_device_fleet1_idx` (`fleet_id` ASC) VISIBLE,
  CONSTRAINT `fk_fleet_has_device_fleet1`
    FOREIGN KEY (`fleet_id`)
    REFERENCES `bnt2`.`fleet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fleet_has_device_device1`
    FOREIGN KEY (`device_id`)
    REFERENCES `bnt2`.`device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bnt2`.`invite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bnt2`.`invite` (
  `player_id` INT UNSIGNED NOT NULL,
  `team_id` INT UNSIGNED NOT NULL,
  `message` TEXT NULL,
  `stamp` DATETIME NULL,
  PRIMARY KEY (`player_id`, `team_id`),
  INDEX `fk_player_has_team_team1_idx` (`team_id` ASC) VISIBLE,
  INDEX `fk_player_has_team_player1_idx` (`player_id` ASC) VISIBLE,
  CONSTRAINT `fk_player_has_team_player1`
    FOREIGN KEY (`player_id`)
    REFERENCES `bnt2`.`player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_player_has_team_team1`
    FOREIGN KEY (`team_id`)
    REFERENCES `bnt2`.`team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
